<link rel="stylesheet" href="./css/about.css">
<?php 
include_once('./nav.php');
?>
  <div class="background-img"></div>
    
  <section class="about-main">
        <h1> About Us </h1>
    </section>

    <section class="why-choose-us">
        <h1> WHY CHOOSE US  </h1>
        <div class="icons">
            <div class="icon">
                <i class="fa-solid fa-users"></i>
                <h3> EXTENSIVE EXPERIENCE </h3>
            </div>
            <div class="icon">
                <i class="fa-solid fa-pen"></i>
                <h3> EXTENSIVE EXPERIENCE </h3>
            </div>
            <div class="icon">
                <i class="fa-solid fa-gears"></i>
                <h3> EXTENSIVE EXPERIENCE </h3>
            </div>
            <div class="icon">
                <i class="fa-regular fa-star"></i>
                <h3> EXTENSIVE EXPERIENCE </h3>
            </div>
        </div>
</section>

    <section class="about-p">
       <div class="p1">
        <p> Our website aims to help people to design their home in an efficient way by providing different types theme designs and aspects of finishes, beginning from the supplies of finishing materials and services till your home door.In addition, we link the user to the experienced workers, contractors, designers, and engineers to make your dream home come true.</p>
<p>  Our website targets all classes with variety of high and low price of the engineer’s.</p>
</div>

<div class="p2">
<p> Our mission is to help people who seek help in designing and decorating their houses with good materials yet efficient prices through our different types of designs suitable for all categories of social classes. With using our website, we provide qualified and trusted designers, contractors, and engineers to help fulfil your dream house</p>

<p>Our Vision is guaranteeing their comfort throughout the process by providing all the client's needs beginning from picking suitable contractors till decorating and furnishing it</p>
</div>
    </section>

<section class="who-we">
    <h1> WHO WE ARE </h1>
    <article>
    Our company is generated by a group of colleagues who thought together about a common issue facing the individuals in Egypt who seek to build their dream home but don't know from where to start and who to contact. We all-together got inspired to create a website solving all those combined issues with the proper help from professionals and experts. We are licensed, bonded, and insured for excellence, reliability, and high-quality work for our clients. Our experienced and dedicated team is here to accompany you every step of the way– from picking a worker till the end of implementation.
Our priority is to ensure your satisfaction and peace of mind, and our goal is to provide you with superb results.
    </article>

</section>


    <section class="why-choose-us">
        <h1> FOUNDERS  </h1>
        <div class="icons">
            <div class="icon">
                <img class="image3" src="./suppliers/basel.jpeg">
            </div>
            <div class="icon">
                <img class="image" src="./suppliers/nada.jpeg">
            </div>
            <div class="icon">
                <img class="image1" src="./suppliers/omar.jpeg">
            </div>
            <div class="icon">
                <img class="image" src="./suppliers/sara.jpeg">
            </div>
            <div class="icon">
                <img class="image2" src="./suppliers/gelo.jpeg">
            </div>
            <div class="icon">
                <img class="image" src="./suppliers/tata.jpeg">
            </div>
        </div>
    </section>
    
<?php 
include_once('./footer.php');
?>