<link rel="stylesheet" href="./css/footer.css">
<footer class="main-footer">
        <div class="company">
        <a href="./index.php" class="logo"><img src="./images/logo.png"> <span class="hide">t</span><span>awakol</span> </a>
            <ul class="nav">
                <li><a href="./index.php">Home</a></li>
                <li><a href="./about.php">About</a></li>
                <li><a href="./service.php"> Services </a></li>
                <li><a href="./gallery.php">Gallery</a></li>
                <li><a href="./workers.php">Workers</a></li>
            </ul>
            <div class="copy"> Copyright © <?php echo date("Y") ;?> All rights reserved </div>
        </div>

        <div class="find">
                <h2> Contact Us </h2>
            <div class="box">
                <div class="icon"><i class="fa-solid fa-location-dot"></i></div> <h3> cario, maadi 3033 </h3>
            </div>
            <div class="box">
                <div class="icon"><i class="fa-solid fa-phone"></i></div> <h3> 19991 </h3>
            </div>
            <div class="box">
                <div class="icon"><i class="fa-solid fa-envelope"></i></div> <h3> info@tawakolgroup.com </h3>
            </div>
        </div>

        <div class="about">
            <h2> about us </h2>
            <p> Our company is generated by a group of colleagues who thought together about a common issue facing the individuals in Egypt who seek to build their dream home but don't know from where to start and who to contact. We all-together got inspired to create a website solving all those combined issues with the proper help from professionals and experts.</p>
            <ul class="icons-links">
                <li><a href=""> <i class="fa-regular fa-circle-question"></i> </a></li>
                <li><a href="https://www.instagram.com/tawakolgroup/" target="_blank"> <i class="fab fa-instagram"></i> </a>
                </li>
                <li><a href="https://www.facebook.com/profile.php?id=100064381440771" target="_blank"><i
                            class="fab fa-facebook-f"></i> </a></li>
                <li><a href=""> <i class="fa-regular fa-message"></i> </a></li>
            </ul>
        </div>
    </footer>
    <script src="./js/nav.js" defer></script>
</body>
</html>